name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Scala v${{ matrix.scala }} / Scala.JS v${{ matrix.scalajs }} / Java v${{ matrix.java }}
    strategy:
      matrix:
        include:
          - java: 8
            scala: 2.12.14
            scalajs: 0.6.33
          - java: 14
            scala: 2.13.6
            scalajs: 0.6.33
          - java: 8
            scala: 2.12.14
            scalajs: 1.x
          - java: 14
            scala: 2.13.6
            scalajs: 1.x

    steps:

      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.${{ matrix.java }}

      - name: Cache sbt
        uses: coursier/cache-action@v6

      - name: Checking your code format
        run: sbt scalafmtCheck

      - name: Build and test
        shell: bash
        run: SCALAJS_VERSION=${{ matrix.scalajs }} sbt clean test
